#!/bin/bash
set -e

# Use gdate on macOS if available
if command -v gdate > /dev/null; then
  DATE_CMD="gdate"
else
  DATE_CMD="date"
fi

# Extract previous activity if it exists
PREVIOUS_ACTIVITY=$(mktemp)
if [ -f activity.md ]; then
    HEADER=$(grep -m 1 "^| " activity.md || true)
    if echo "$HEADER" | grep -q "Activity Date"; then
        grep "^| " activity.md | grep -v "Activity Date" | grep -v ":---" | while read -r line; do
            date_part=$(echo "$line" | cut -d'|' -f2 | xargs)
            clean_date=$(echo "$date_part" | sed 's/[^0-9 :-]//g' | sed 's/^ *//;s/ *$//')
            repo_part=$(echo "$line" | cut -d'|' -f3 | xargs)
            [ -n "$repo_part" ] && [ -n "$clean_date" ] && echo "$repo_part|$clean_date||" >> "$PREVIOUS_ACTIVITY"
        done
    else
        grep "^| " activity.md | grep -v "Repository" | grep -v ":---" | while read -r line; do
            repo_part=$(echo "$line" | cut -d'|' -f2 | xargs)
            commit_part=$(echo "$line" | cut -d'|' -f3 | xargs | sed 's/[^0-9 :-]//g' | xargs)
            pr_part=$(echo "$line" | cut -d'|' -f4 | xargs | sed 's/[^0-9 :-]//g' | xargs)
            issue_part=$(echo "$line" | cut -d'|' -f5 | xargs | sed 's/[^0-9 :-]//g' | xargs)
            [ -n "$repo_part" ] && echo "$repo_part|$commit_part|$pr_part|$issue_part" >> "$PREVIOUS_ACTIVITY"
        done
    fi
fi

# Header
cat <<EOF > activity.md
# Labs Activity Sorted by Project (Lab)

**Last updated: $($DATE_CMD -u "+%Y-%m-%d %H:%M:%S UTC")**

This report is automatically generated by querying the GitHub API for the most recent activity (commits, pull requests, and issues) in the tracked repositories. Projects are grouped by their display names.
EOF

ALL_REPOS_TMP=$(mktemp)
QUERY='query($owner:String!, $name:String!) {
  repository(owner: $owner, name: $name) {
    pushedAt
    pullRequests(first: 1, orderBy: {field: UPDATED_AT, direction: DESC}) { nodes { updatedAt } }
    issues(first: 1, orderBy: {field: UPDATED_AT, direction: DESC}) { nodes { updatedAt } }
  }
}'

echo "Fetching activity..."
NUM_LABS=$(jq '.labs | length' repos.json)
for ((i=0; i<NUM_LABS; i++)); do
    DISPLAY_NAME=$(jq -r --argjson i "$i" '.labs[$i].display_name' repos.json)
    NUM_REPOS=$(jq --argjson i "$i" ".labs[$i].repositories | length" repos.json)
    for ((j=0; j<NUM_REPOS; j++)); do
        ORG=$(jq -r --argjson i "$i" --argjson j "$j" '.labs[$i].repositories[$j].org' repos.json)
        REPO=$(jq -r --argjson i "$i" --argjson j "$j" '.labs[$i].repositories[$j].name' repos.json)
        echo "  Checking ${ORG}/${REPO} (${DISPLAY_NAME})..."
        RESULT=$(gh api graphql -f query="$QUERY" -F owner="$ORG" -F name="$REPO" --jq '.data.repository' 2>/dev/null || echo "null")
        if [ "$RESULT" != "null" ] && [ -n "$RESULT" ]; then
            PUSHED_AT=$(echo "$RESULT" | jq -r '.pushedAt // empty')
            PR_UPDATED_AT=$(echo "$RESULT" | jq -r '.pullRequests.nodes[0].updatedAt // empty')
            ISSUE_UPDATED_AT=$(echo "$RESULT" | jq -r '.issues.nodes[0].updatedAt // empty')
            COMMIT_TS=0; PR_TS=0; ISSUE_TS=0
            [ -n "$PUSHED_AT" ] && COMMIT_TS=$($DATE_CMD -d "$PUSHED_AT" "+%s" 2>/dev/null || echo 0)
            [ -n "$PR_UPDATED_AT" ] && PR_TS=$($DATE_CMD -d "$PR_UPDATED_AT" "+%s" 2>/dev/null || echo 0)
            [ -n "$ISSUE_UPDATED_AT" ] && ISSUE_TS=$($DATE_CMD -d "$ISSUE_UPDATED_AT" "+%s" 2>/dev/null || echo 0)
            MAX_TS=$COMMIT_TS; [ $PR_TS -gt $MAX_TS ] && MAX_TS=$PR_TS; [ $ISSUE_TS -gt $MAX_TS ] && MAX_TS=$ISSUE_TS
            echo "$MAX_TS|$COMMIT_TS|$PR_TS|$ISSUE_TS|$ORG|$REPO|$DISPLAY_NAME" >> "$ALL_REPOS_TMP"
        fi
    done
done

LAB_NAMES=$(jq -r '.labs[].display_name' repos.json | sort -u)
IFS=$'\n'
for lab in $LAB_NAMES; do
    if grep -q "|$lab$" "$ALL_REPOS_TMP"; then
        echo "" >> activity.md
        echo "## $lab" >> activity.md
        echo "| Repository | Latest Commit | Latest PR | Latest Issue | Link |" >> activity.md
        echo "| :--- | :--- | :--- | :--- | :--- |" >> activity.md
        grep "|$lab$" "$ALL_REPOS_TMP" | sort -rn | while IFS='|' read max_ts commit_ts pr_ts issue_ts org repo display_name; do
            repo_full="$org/$repo"
            PREV_LINE=$(grep "^$repo_full|" "$PREVIOUS_ACTIVITY" | head -n 1 || true)
            p_commit=$(echo "$PREV_LINE" | cut -d'|' -f2); p_pr=$(echo "$PREV_LINE" | cut -d'|' -f3); p_issue=$(echo "$PREV_LINE" | cut -d'|' -f4)
            
            format_date() {
                local ts=$1; local prev=$2
                [ "$ts" -eq 0 ] && echo "n/a" && return
                local ds=$($DATE_CMD -d "@$ts" "+%Y-%m-%d %H:%M:%S")
                if [ -z "$prev" ]; then echo "$\color{blue}{\text{${ds}}}$"
                elif [ "$prev" != "$ds" ]; then echo "$\color{green}{\text{${ds}}}$"
                else echo "$ds"; fi
            }
            
            printf "| %s | %s | %s | %s | [github.com/%s/%s](https://github.com/%s/%s) |\n" \
                "$repo_full" "$(format_date "$commit_ts" "$p_commit")" "$(format_date "$pr_ts" "$p_pr")" "$(format_date "$issue_ts" "$p_issue")" "$org" "$repo" "$org" "$repo" >> activity.md
        done
    fi
done
rm "$ALL_REPOS_TMP" "$PREVIOUS_ACTIVITY"

python3 generate_reports.py
